---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)

data(ny_noaa) 


ny_noaa = ny_noaa%>%
  slice_sample(n=10000) %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    snow_mm = snow,
    snow = round(snow_mm * 0.03937 * 4) / 4)
```

NY NOAA Data {data-width=650}
-----------------------------------------------------------------------

### Precipitation by year

```{r}
ny_noaa %>%
  drop_na(prcp)%>%
  plot_ly(x= ~year, y=~prcp, alpha = .5,
          type = "bar")
```

More charts {data-width=350}
-----------------------------------------------------------------------

### Snowfall by minimum temperature

```{r}
ny_noaa %>%
  drop_na(snow_mm) %>%
  filter(snow_mm > 0) %>%
  plot_ly(x = ~tmin, y = ~snow_mm, alpha = .5,
          type = "box")
```

### Temperature extremes by weather station in 2010

```{r}
ny_noaa %>%
  filter(year == 2010) %>%
  drop_na(tmax) %>%
  plot_ly(x = ~id, y= ~tmax, color = ~tmin, alpha = .5,
          type = "scatter", mode = "markers")
```

